name: clearpath_config_ci

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  build_and_test:
    name: jazzy
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: jazzy, ROS_REPO: testing}
          - {ROS_DISTRO: jazzy, ROS_REPO: main}
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

  clearpath_config_src_ci:
    name: Jazzy Clearpath Source
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci_step
        with:
          target-ros2-distro: jazzy

  clearpath_generator_tests_ci:
    name: Jazzy Clearpath Generator Tests
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - uses: actions/checkout@v3
      - name: "[Repositories Updater] Checkout action"
        uses: actions/checkout@v3
        with:
          repository: clearpathrobotics/repos-dep-update-action
          ref: 0.0.4
          path: repos-dep-update-action
      - name: "[Repositories Updater] Install dependencies"
        run: |
          apt-get update
          apt-get install -y jq git python3 python3-pip
          python3 -m pip install yq --break-system-packages
      - name: "[Repositories Updater] Extract branch name"
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: "[Repositories Updater] Run action"
        uses: ./repos-dep-update-action/
        with:
          branch: ${{ steps.extract_branch.outputs.branch }}
          input: downstream.repos
          output: updated_downstream.repos
      - name: "[Repositories Updater] Print updated repositories"
        run: |
          cat updated_downstream.repos
      - uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci_step
        with:
          target-ros2-distro: jazzy
          vcs-repo-file-url: update_downstream.repos